version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - "bin"
    - "tmp"
    - "testdata"

formatters:
  enable:
    - gofmt

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

